export const productsExample = [
  {
    id: 'duiogasdlasjhkdabjklsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'duasjhkdabiogasdljklsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'dukdabjkliogasdlasjhsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'jhkdabjduiogasdlasklsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'dasdlasjhkdabjkluiogsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'asdasoid',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'asdopiapsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'asiopdaoipsd',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
  {
    id: 'fuiaopjdopiasdjpioa',
    text: 'Placa de Vídeo RTX 3060 Ventus 2X MSI NVIDIA GeForce, 12GB GDDR6, DLSS, Ray Tracing - RTX 3060 Ventus 2X 12G OC',
    price: '29,35',
    units: '50',
    img: 'Placadevideo',
    seller: 'Cleito',
  },
]
